'use client';

import { useState } from "react";
import { AviaSearchTicket, AviaTicketModal } from "@/modules/flights/components";
import { ITicket } from "../../interface/ticket";



export const AviaSearchResult = () => {
    const [tickets] = useState<ITicket[]>([
        {
            price: 458,
            airline: 'EasyJet',
            airlineLogo: 'https://placehold.co/200x100/orange/white?text=EasyJet',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'London',
            arrivalCity: 'Paris',
            departureAirport: 'LGW',
            arrivalAirport: 'CDG',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 161,
            remainingTickets: 4,
            tag: 'Cheapest',
            baggageIncluded: false,
        },
        {
            price: 745,
            airline: 'Ryanair',
            airlineLogo: 'https://placehold.co/200x100/blue/white?text=Ryanair',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Berlin',
            arrivalCity: 'Rome',
            departureAirport: 'TXL',
            arrivalAirport: 'FCO',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 191,
            remainingTickets: 6,
            tag: 'Morning',
            baggageIncluded: false,
        },
        {
            price: 532,
            airline: 'Lufthansa',
            airlineLogo: 'https://placehold.co/200x100/yellow/black?text=Lufthansa',
            departureTime: '14:15',
            arrivalTime: '16:45',
            departureCity: 'Frankfurt',
            arrivalCity: 'Madrid',
            departureAirport: 'FRA',
            arrivalAirport: 'MAD',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '2h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 175,
            remainingTickets: 3,
            tag: 'Afternoon',
            baggageIncluded: false,
        },
        {
            price: 689,
            airline: 'KLM',
            airlineLogo: 'https://placehold.co/200x100/lightblue/white?text=KLM',
            departureTime: '07:30',
            arrivalTime: '09:15',
            departureCity: 'Amsterdam',
            arrivalCity: 'Copenhagen',
            departureAirport: 'AMS',
            arrivalAirport: 'CPH',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 45m',
            direct: true,
            stops: 0,
            baggagePrice: 180,
            remainingTickets: 5,
            tag: 'Early',
            baggageIncluded: false,
        },
        {
            price: 458,
            airline: 'EasyJet',
            airlineLogo: 'https://placehold.co/200x100/orange/white?text=EasyJet',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'London',
            arrivalCity: 'Paris',
            departureAirport: 'LGW',
            arrivalAirport: 'CDG',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 161,
            remainingTickets: 4,
            tag: 'Cheapest',
            baggageIncluded: false,
        },
        {
            price: 745,
            airline: 'Ryanair',
            airlineLogo: 'https://placehold.co/200x100/blue/white?text=Ryanair',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Berlin',
            arrivalCity: 'Rome',
            departureAirport: 'TXL',
            arrivalAirport: 'FCO',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 191,
            remainingTickets: 6,
            tag: 'Morning',
            baggageIncluded: false,
        },
        {
            price: 532,
            airline: 'Lufthansa',
            airlineLogo: 'https://placehold.co/200x100/yellow/black?text=Lufthansa',
            departureTime: '14:15',
            arrivalTime: '16:45',
            departureCity: 'Frankfurt',
            arrivalCity: 'Madrid',
            departureAirport: 'FRA',
            arrivalAirport: 'MAD',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '2h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 175,
            remainingTickets: 3,
            tag: 'Afternoon',
            baggageIncluded: false,
        },
        {
            price: 689,
            airline: 'KLM',
            airlineLogo: 'https://placehold.co/200x100/lightblue/white?text=KLM',
            departureTime: '07:30',
            arrivalTime: '09:15',
            departureCity: 'Amsterdam',
            arrivalCity: 'Copenhagen',
            departureAirport: 'AMS',
            arrivalAirport: 'CPH',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 45m',
            direct: true,
            stops: 0,
            baggagePrice: 180,
            remainingTickets: 5,
            tag: 'Early',
            baggageIncluded: false,
        },
        {
            price: 458,
            airline: 'EasyJet',
            airlineLogo: 'https://placehold.co/200x100/orange/white?text=EasyJet',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'London',
            arrivalCity: 'Paris',
            departureAirport: 'LGW',
            arrivalAirport: 'CDG',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 161,
            remainingTickets: 4,
            tag: 'Cheapest',
            baggageIncluded: false,
        },
        {
            price: 745,
            airline: 'Ryanair',
            airlineLogo: 'https://placehold.co/200x100/blue/white?text=Ryanair',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Berlin',
            arrivalCity: 'Rome',
            departureAirport: 'TXL',
            arrivalAirport: 'FCO',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 191,
            remainingTickets: 6,
            tag: 'Morning',
            baggageIncluded: false,
        },
        {
            price: 532,
            airline: 'Lufthansa',
            airlineLogo: 'https://placehold.co/200x100/yellow/black?text=Lufthansa',
            departureTime: '14:15',
            arrivalTime: '16:45',
            departureCity: 'Frankfurt',
            arrivalCity: 'Madrid',
            departureAirport: 'FRA',
            arrivalAirport: 'MAD',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '2h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 175,
            remainingTickets: 3,
            tag: 'Afternoon',
            baggageIncluded: false,
        },
        {
            price: 689,
            airline: 'KLM',
            airlineLogo: 'https://placehold.co/200x100/lightblue/white?text=KLM',
            departureTime: '07:30',
            arrivalTime: '09:15',
            departureCity: 'Amsterdam',
            arrivalCity: 'Copenhagen',
            departureAirport: 'AMS',
            arrivalAirport: 'CPH',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 45m',
            direct: true,
            stops: 0,
            baggagePrice: 180,
            remainingTickets: 5,
            tag: 'Early',
            baggageIncluded: false,
        },
        {
            price: 458,
            airline: 'EasyJet',
            airlineLogo: 'https://placehold.co/200x100/orange/white?text=EasyJet',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'London',
            arrivalCity: 'Paris',
            departureAirport: 'LGW',
            arrivalAirport: 'CDG',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 161,
            remainingTickets: 4,
            tag: 'Cheapest',
            baggageIncluded: false,
        },
        {
            price: 745,
            airline: 'Ryanair',
            airlineLogo: 'https://placehold.co/200x100/blue/white?text=Ryanair',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Berlin',
            arrivalCity: 'Rome',
            departureAirport: 'TXL',
            arrivalAirport: 'FCO',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 191,
            remainingTickets: 6,
            tag: 'Morning',
            baggageIncluded: false,
        },
        {
            price: 532,
            airline: 'Lufthansa',
            airlineLogo: 'https://placehold.co/200x100/yellow/black?text=Lufthansa',
            departureTime: '14:15',
            arrivalTime: '16:45',
            departureCity: 'Frankfurt',
            arrivalCity: 'Madrid',
            departureAirport: 'FRA',
            arrivalAirport: 'MAD',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '2h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 175,
            remainingTickets: 3,
            tag: 'Afternoon',
            baggageIncluded: false,
        },
        {
            price: 689,
            airline: 'KLM',
            airlineLogo: 'https://placehold.co/200x100/lightblue/white?text=KLM',
            departureTime: '07:30',
            arrivalTime: '09:15',
            departureCity: 'Amsterdam',
            arrivalCity: 'Copenhagen',
            departureAirport: 'AMS',
            arrivalAirport: 'CPH',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 45m',
            direct: true,
            stops: 0,
            baggagePrice: 180,
            remainingTickets: 5,
            tag: 'Early',
            baggageIncluded: false,
        },
        {
            price: 458,
            airline: 'EasyJet',
            airlineLogo: 'https://placehold.co/200x100/orange/white?text=EasyJet',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'London',
            arrivalCity: 'Paris',
            departureAirport: 'LGW',
            arrivalAirport: 'CDG',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 161,
            remainingTickets: 4,
            tag: 'Cheapest',
            baggageIncluded: false,
        },
        {
            price: 745,
            airline: 'Ryanair',
            airlineLogo: 'https://placehold.co/200x100/blue/white?text=Ryanair',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Berlin',
            arrivalCity: 'Rome',
            departureAirport: 'TXL',
            arrivalAirport: 'FCO',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 191,
            remainingTickets: 6,
            tag: 'Morning',
            baggageIncluded: false,
        },
        {
            price: 532,
            airline: 'Lufthansa',
            airlineLogo: 'https://placehold.co/200x100/yellow/black?text=Lufthansa',
            departureTime: '14:15',
            arrivalTime: '16:45',
            departureCity: 'Frankfurt',
            arrivalCity: 'Madrid',
            departureAirport: 'FRA',
            arrivalAirport: 'MAD',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '2h 30m',
            direct: true,
            stops: 0,
            baggagePrice: 175,
            remainingTickets: 3,
            tag: 'Afternoon',
            baggageIncluded: false,
        },
        {
            price: 689,
            airline: 'KLM',
            airlineLogo: 'https://placehold.co/200x100/lightblue/white?text=KLM',
            departureTime: '07:30',
            arrivalTime: '09:15',
            departureCity: 'Amsterdam',
            arrivalCity: 'Copenhagen',
            departureAirport: 'AMS',
            arrivalAirport: 'CPH',
            departureDate: 'Sep 16, Mon',
            arrivalDate: 'Sep 16, Mon',
            duration: '1h 45m',
            direct: true,
            stops: 0,
            baggagePrice: 180,
            remainingTickets: 5,
            tag: 'Early',
            baggageIncluded: false,
        },
    ]);

    const [selectedTicket, setSelectedTicket] = useState<ITicket | null>(null);

    const handleTicketSelect = (ticket: ITicket) => {
        setSelectedTicket(ticket);
    };

    const handleCloseModal = () => {
        setSelectedTicket(null);
    };

    return (

        <div className="md:w-3/4 lg:w-full">
            {tickets.map((ticket, index) => (
                <AviaSearchTicket key={index} ticket={ticket} onSelect={() => handleTicketSelect(ticket)} />
            ))}
            {selectedTicket && <AviaTicketModal ticket={selectedTicket} onClose={handleCloseModal} />}
        </div>
    );
}