'use client';

import { useState } from "react";
import { AviaSearchTicket, AviaTicketModal } from "@/modules/flights/components";
import { ITicket } from "../../interface/ticket";



export const AviaSearchResult = () => {
    const [tickets] = useState<ITicket[]>([
        {
            price: 4583,
            airline: 'Победа',
            airlineLogo: '/assets/images/S7.avif',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1618,
            remainingTickets: 4,
            tag: 'Самый дешёвый',
            baggageIncluded: false,
        },
        {
            price: 7456,
            airline: 'Победа',
            airlineLogo: '/assets/images/SU.avif',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1914,
            remainingTickets: 6,
            tag: 'Вылет утром',
            baggageIncluded: false,
        },
        {
            price: 4583,
            airline: 'Победа',
            airlineLogo: '/assets/images/S7.avif',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1618,
            remainingTickets: 4,
            tag: 'Самый дешёвый',
            baggageIncluded: false,
        },
        {
            price: 7456,
            airline: 'Победа',
            airlineLogo: '/assets/images/SU.avif',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1914,
            remainingTickets: 6,
            tag: 'Вылет утром',
            baggageIncluded: false,
        },
        {
            price: 4583,
            airline: 'Победа',
            airlineLogo: '/assets/images/S7.avif',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1618,
            remainingTickets: 4,
            tag: 'Самый дешёвый',
            baggageIncluded: false,
        },
        {
            price: 7456,
            airline: 'Победа',
            airlineLogo: '/assets/images/SU.avif',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1914,
            remainingTickets: 6,
            tag: 'Вылет утром',
            baggageIncluded: false,
        },
        {
            price: 4583,
            airline: 'Победа',
            airlineLogo: '/assets/images/S7.avif',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1618,
            remainingTickets: 4,
            tag: 'Самый дешёвый',
            baggageIncluded: false,
        },
        {
            price: 7456,
            airline: 'Победа',
            airlineLogo: '/assets/images/SU.avif',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1914,
            remainingTickets: 6,
            tag: 'Вылет утром',
            baggageIncluded: false,
        },
        {
            price: 4583,
            airline: 'Победа',
            airlineLogo: '/assets/images/S7.avif',
            departureTime: '22:00',
            arrivalTime: '23:30',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1618,
            remainingTickets: 4,
            tag: 'Самый дешёвый',
            baggageIncluded: false,
        },
        {
            price: 7456,
            airline: 'Победа',
            airlineLogo: '/assets/images/SU.avif',
            departureTime: '09:40',
            arrivalTime: '11:10',
            departureCity: 'Москва',
            arrivalCity: 'Москва',
            departureAirport: 'DME',
            arrivalAirport: 'DME',
            departureDate: '16 сен, пн',
            arrivalDate: '16 сен, пн',
            duration: '1ч 30м',
            direct: true,
            stops: 0,
            baggagePrice: 1914,
            remainingTickets: 6,
            tag: 'Вылет утром',
            baggageIncluded: false,
        },
    ]);

    const [selectedTicket, setSelectedTicket] = useState<ITicket | null>(null);

    const handleTicketSelect = (ticket: ITicket) => {
        setSelectedTicket(ticket);
    };

    const handleCloseModal = () => {
        setSelectedTicket(null);
    };

    return (

        <div className="md:w-3/4">
            {tickets.map((ticket, index) => (
                <AviaSearchTicket key={index} ticket={ticket} onSelect={() => handleTicketSelect(ticket)} />
            ))}
            {selectedTicket && <AviaTicketModal ticket={selectedTicket} onClose={handleCloseModal} />}
        </div>
    );
}